import React, { useState, useEffect } from 'react';

import { Loader, FormField, Cards } from '../components/index.js';

const Home = () => {
  const [loading, setLoading] = useState(false);
  const [allPosts, setAllPosts] = useState([null]);
  const [searchText, setSearchText] = useState('');

  return (
    <main className="sm:p-8 px-4 py-8 w-full bg-[#f9fafe] min-h-[calc(100vh-73px)]">
      <section className="max-w-7xl mx-auto">
        <div>
          <h1 className="font-extrabold text-[#222328] text-[32px]">
            The Community Showcase
          </h1>
          <p className="mt-2 text-[#666e75] text-[16px] max-w-3/4">
            Browse through a collection of imaginative abd visually stunning
            images generated by DALL-E AI.
          </p>
        </div>
        <div className="mt-16">
          <FormField />
        </div>
        <div className="mt-10">
          {loading ? (
            <div className="flex justify-center items-center">
              <Loader />
            </div>
          ) : (
            <>
              {searchText && (
                <h2 className="font-medium text-[#666e75] text-xl mb-3">
                  Showing results for{' '}
                  <span className="text-[#222328]">{searchText}</span>
                </h2>
              )}
              <div className="grid lg:grid-cols-4 sm:grid-cols-3 xs:grid-cols-2 grid-cols-1 gap-3">
                {searchText ? (
                  <Cards data={[]} title="No search results found!" />
                ) : (
                  <Cards data={[]} title="No posts found!" />
                )}
              </div>
            </>
          )}
        </div>
      </section>
    </main>
  );
};

export default Home;
